[env:m5stack-atom]
platform = espressif32
board = m5stack-atom
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/MinteliaShip/servoICS.git#Dev
    https://github.com/aed3/PS4-esp32.git
    https://github.com/hideakitai/ArduinoEigen#v0.3.2